<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="Apps/Appliances/test_update.py" name="Apps.Appliances.test_update.UpdateAppliance-20200303214930" skipped="0" tests="2" time="0.011" timestamp="2020-03-03T21:49:30">
	<testcase classname="Apps.Appliances.test_update.UpdateAppliance" file="Apps/Appliances/test_update.py" line="87" name="test_update_app_bad_app_id" time="0.005" timestamp="2020-03-03T21:49:30">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Appliances.test_update.UpdateAppliance" file="Apps/Appliances/test_update.py" line="28" name="test_update_appliance_allCorrect" time="0.006" timestamp="2020-03-03T21:49:30">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
