<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="Apps/Properties/test_info.py" name="Apps.Properties.test_info.SendBackLists-20200303214930" skipped="0" tests="1" time="0.003" timestamp="2020-03-03T21:49:31">
	<testcase classname="Apps.Properties.test_info.SendBackLists" file="Apps/Properties/test_info.py" line="26" name="test_create_property_allCorrect" time="0.003" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_info.py", line 52, in test_create_property_allCorrect
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
