<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="1" failures="0" file="Apps/ServiceRequest/test_get.py" name="Apps.ServiceRequest.test_get.GetServiceRequest-20200303214930" skipped="0" tests="1" time="0.018" timestamp="2020-03-03T21:49:30">
	<testcase classname="Apps.ServiceRequest.test_get.GetServiceRequest" file="Apps/ServiceRequest/test_get.py" line="29" name="test_update_service_request_allCorrect" time="0.018" timestamp="2020-03-03T21:49:30">
		<error message="Expecting value: line 1 column 1 (char 0)" type="JSONDecodeError">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/ServiceRequest/test_get.py", line 95, in test_update_service_request_allCorrect
    responseData = getInfoGet(REQ_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 61, in getInfoGet
    response = client.get(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/rest_framework/test.py", line 286, in get
    response = super().get(path, data=data, **extra)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/rest_framework/test.py", line 203, in get
    return self.generic('GET', path, **r)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/rest_framework/test.py", line 232, in generic
    method, path, data, content_type, secure, **extra)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/test/client.py", line 421, in generic
    return self.request(**r)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/rest_framework/test.py", line 283, in request
    return super().request(**kwargs)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/rest_framework/test.py", line 235, in request
    request = super().request(**kwargs)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/test/client.py", line 496, in request
    raise exc_value
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/ServiceRequest/views.py", line 145, in get
    inData = json.loads(request.body)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
