<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="6" failures="0" file="Apps/Properties/test_create.py" name="Apps.Properties.test_create.CreateProperty-20200303214930" skipped="0" tests="6" time="0.015" timestamp="2020-03-03T21:49:31">
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="32" name="test_create_property_allCorrect" time="0.005" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 60, in test_create_property_allCorrect
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="139" name="test_create_property_bad_field_bath" time="0.002" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 151, in test_create_property_bad_field_bath
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="123" name="test_create_property_bad_field_city" time="0.001" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 134, in test_create_property_bad_field_city
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="156" name="test_create_property_bad_field_mult" time="0.001" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 165, in test_create_property_bad_field_mult
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="107" name="test_create_property_bad_field_street" time="0.002" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 118, in test_create_property_bad_field_street
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Apps.Properties.test_create.CreateProperty" file="Apps/Properties/test_create.py" line="67" name="test_create_property_duplicate" time="0.004" timestamp="2020-03-03T21:49:31">
		<error message="Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name." type="NoReverseMatch">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_create.py", line 103, in test_create_property_duplicate
    responseData = getInfoPost(PROP_VIEW, data)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/helperFuncsForTesting.py", line 55, in getInfoPost
    response = client.post(path=reverse(endpoint), data=data, format="json")
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/Users/aberard/Programming/HomePairs/django_env/lib/python3.7/site-packages/django/urls/resolvers.py", line 677, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'property_view' not found. 'property_view' is not a valid view function or pattern name.
]]>		</error>
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
