<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
	<testsuite errors="0" failures="1" file="Apps/Properties/test_update.py" name="Apps.Properties.test_update.UpdateProperty-20200220051716" skipped="0" tests="5" time="0.529" timestamp="2020-02-20T05:17:17">
		<testcase classname="Apps.Properties.test_update.UpdateProperty" file="Apps/Properties/test_update.py" line="130" name="test_create_property_bad_field_bath" time="0.031" timestamp="2020-02-20T05:17:16">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="Apps.Properties.test_update.UpdateProperty" file="Apps/Properties/test_update.py" line="112" name="test_create_property_bad_field_city" time="0.006" timestamp="2020-02-20T05:17:16">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="Apps.Properties.test_update.UpdateProperty" file="Apps/Properties/test_update.py" line="149" name="test_create_property_bad_field_mult" time="0.005" timestamp="2020-02-20T05:17:16">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="Apps.Properties.test_update.UpdateProperty" file="Apps/Properties/test_update.py" line="94" name="test_create_property_bad_field_street" time="0.005" timestamp="2020-02-20T05:17:16">
			<system-out>
<![CDATA[]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
		<testcase classname="Apps.Properties.test_update.UpdateProperty" file="Apps/Properties/test_update.py" line="36" name="test_update_property_allCorrect" time="0.483" timestamp="2020-02-20T05:17:17">
			<failure message="'failure' != 'success'
- failure
+ success
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/unittest/mock.py", line 1204, in patched
    return func(*args, **keywargs)
  File "/Users/aberard/Programming/HomePairs/2.0/homepairs/HomepairsApp/Apps/Properties/test_update.py", line 85, in test_update_property_allCorrect
    self.assertEqual(responseData.get(STATUS), SUCCESS)
AssertionError: 'failure' != 'success'
- failure
+ success

]]>			</failure>
			<system-out>
<![CDATA[TEMP RPOP
{'streetAddress': '1054 Saint James Ct.', 'city': 'San Dimas', 'state': 'CA', 'numBath': 2.0, 'numBed': 5, 'maxTenants': 8, 'rooId': 'lmnopqrs', 'pm': 'Updating Props'}
TEMP RPOP
{'streetAddress': '1054 Saint James Ct.', 'city': 'San Dimas', 'state': 'CA', 'numBath': 2.0, 'numBed': 5, 'maxTenants': 8, 'rooId': 'lmnopqrs', 'pm': 'Updating Props'}
]]>			</system-out>
			<system-err>
<![CDATA[]]>			</system-err>
		</testcase>
	</testsuite>
</testsuites>
